/* orm.addresses */
export const CREATE_ADDRESS = 'CREATE_ADDRESS';
export const REMOVE_ADDRESS = 'REMOVE_ADDRESS';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const SWAP_ADDRESSES = 'SWAP_ADDRESSES';

/* ui.nav */
export const TOGGLE_COINS_MENU = 'TOGGLE_COINS_MENU';
export const SWITCH_COIN = 'SWITCH_COIN';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const SWAP_FAVORITES = 'SWAP_FAVORITES';
export const HIDE_SORTING_HELP_MESSAGE = 'HIDE_SORTING_HELP_MESSAGE';

/* ui.list */
export const TOGGLE_ADDRESS_OPTIONS_MENU = 'TOGGLE_ADDRESS_OPTIONS_MENU';
export const SWITCH_ADDRESS = 'SWITCH_ADDRESS';

/* ui.form */
export const OPEN_CREATE_ADDRESS_FORM = 'OPEN_CREATE_ADDRESS_FORM';
export const OPEN_EDIT_ADDRESS_FORM = 'OPEN_EDIT_ADDRESS_FORM';
export const CLOSE_FORM = 'CLOSE_FORM';
export const EDIT_STRING = 'EDIT_STRING';
export const EDIT_NAME = 'EDIT_NAME';

/* ui.modals */
export const TOGGLE_DELETE_DIALOG = 'TOGGLE_DELETE_DIALOG';
export const TOGGLE_QR_CODE_DIALOG = 'TOGGLE_QR_CODE_DIALOG';
